Practice2 dani
DanielHidalgoChica/practicas_pdoo pull request #5
Opened 2024-04-01 11:21 UTC by DanielHidalgoChica

Échale un ojo y a ver cómo lo ves. Los commits son los míos locales, no dan mucha info sobre el trabajo.

2024-04-01 17:54 UTC, luis-valdivieso commented on Irrgarten/src/irrgarten/Game.java
> +    public Game(ArrayList<Player> players, ArrayList<Monster> monsters) {
```suggestion
    public Game (int nplayers){
```
En el diagrama de clases especifica la cabecera del método así, creo que no es necesario pasarle los parámetros de jugadores y monstruos (solo iniciarlos dentro) ya que luego en configureLabyrinth() se ponen

2024-04-01 17:58 UTC, luis-valdivieso commented on Irrgarten/src/irrgarten/Game.java
> +    }
```suggestion
    public Game(int nplayers){
        log = "";
        char number;
        // Number of rows and columns
        int nRows = 5, nCols = 5;
        // int exitRow = Dice.randomPos(nRows), exitCol = Dice.randomPos(nCols);
        int exitRow = 1, exitCol = 0;
        players = new ArrayList<Player>(0);
        for (int i = 0; i < nplayers; i++){
            players.add(new Player((char)(i+'0'), Dice.randomIntelligence(), Dice.randomStrength()));
        }
        currentPlayerIndex = Dice.whoStarts(nplayers);
        currentPlayer = players.get(currentPlayerIndex);
        monsters = new ArrayList<Monster> (0);
        labyrinth = new Labyrinth(nRows,nCols,exitRow, exitCol);
        configureLabyrinth();
        
    }
```
Creo que no hace falta pasar los arrays porque se inicializan dentro del propio juego, el de jugadores con el parámetro nplayers y el de monstruos en configureLabyrinth()

2024-04-01 18:00 UTC, luis-valdivieso commented on Irrgarten/src/irrgarten/Game.java
> +	// un laberinto concreto
```suggestion
Monster goblin = new Monster ("Goblin", Dice.randomIntelligence(), Dice.randomStrength());
        labyrinth.addMonster(2,2,goblin);
        monsters.add(goblin);
```

Esto puse yo, es un laberinto simple

2024-04-01 18:08 UTC, luis-valdivieso commented on Irrgarten/src/irrgarten/Labyrinth.java
> +
En este caso yo he creado la instancia de los arrays dentro del propio constructor por aquello de mantener toda la inicialización de los parámetros dentro del constructor. Además no he puesto todo a null pues creo no es necesario, los métodos que modifican los arrays deben encargarse de las posiciones correctas.
`        monsters = new Monster[nRows][nCols];
        labyrinth = new char[nRows][nCols];
        players = new Player[nRows][nCols];
        // We put all the empty blocks
        for (int i = 0; i < this.nRows ; i ++){
            for (int j = 0; j < this.nCols; j++){
                labyrinth[i][j]=EMPTY_CHAR;
            }
        }`

2024-04-01 19:11 UTC, luis-valdivieso requested changes
En general todo bien, realmente he corregido líneas aisladas. Lo más importante que queda por aclarar es el método configureLabyrinth y el constructor de la clase Labyrinth. También falta por hacer un test bueno de esto.

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Monster.rb
> +       @health = @health-1
Al igual que comenté en la clase de java, se puede incluir un atributo de clase @@HEALTH_DECREMENT = -1, pero son cuestiones no tan importantes.

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Monster.rb
> +       @col = col
```suggestion
    set_pos(0,0)
```
Usar la función que después se implementa.

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Player.rb
> +        @consecutive_hits = 0;
```suggestion
        self.reset_hits
```

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Player.rb
> +        @shields.clear()
```suggestion
        @weapons = Array.new
        @shields = Array.new
```
Esto sirve para poder usar resurrect() en el constructor, no se si es menos eficiente que Array.clear(), pero permite la reusabilidad de código.

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Player.rb
> +        @shields = Array.new
```suggestion
        self.resurrect
        set_pos(0,0)
```
Cambios para reutilizar código. La gran pregunta de si la posición debe ser inicializada ya la solucionaremos.

2024-04-01 19:11 UTC, luis-valdivieso commented on Irrgarten_ruby/Player.rb
> +
```suggestion
    def got_wounded
        @health = @health - @@HEALTH_DECREMENT
    end
```
Método que faltaba.

2024-04-02 13:45 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Game.java
> +	// un laberinto concreto
Está bien, sin más. Un poco arbitrario el nombre del monstruo.

2024-04-02 13:49 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Labyrinth.java
> +    private boolean PosOK(int row, int col){
Me suena mucho la mayúscula, en el guión estaría mal, damn.

2024-04-02 13:49 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Labyrinth.java
> +	return "HAY QUE HACER ESTE TO_STRING DE LA CLAS Labyrinth";
Pues correctamente, la verdad que no tenía muy claro si había que describir el estado en forma de log o mostrarlo sin más. Está bien.

2024-04-02 13:51 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Labyrinth.java
> +	return final_pos;
Queda más claro y además resulta que en la mía las filas y las columnas las pensé al revés, perdón.

2024-04-02 13:52 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Monster.java
> +        health -= 1;
Sin más.

2024-04-02 13:53 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Player.java
> +	this.shields = null;
Bomba

2024-04-02 13:56 UTC, DanielHidalgoChica commented on Irrgarten/src/irrgarten/Player.java
> +    }
Coño.

2024-04-02 14:09 UTC, DanielHidalgoChica commented on Irrgarten_ruby/Labyrinth.rb
> +    if (pos_ok(row,col))
Hosita, sí.

2024-04-02 14:11 UTC, DanielHidalgoChica commented on Irrgarten_ruby/Monster.rb
> +       @col = col
¿Por qué 0,0 ?

2024-04-02 14:53 UTC, luis-valdivieso commented on Irrgarten/src/irrgarten/Labyrinth.java
> +    }
```suggestion
    private Monster[][] monsters;
    private Player[][] players;
    private char labyrinth[][];

    // Constructor provisional porque no tengo ni idea
    public Labyrinth(int nRows, int nCols, int exitRow, int exitCol){
	this.exitRow = exitRow;
	this.exitCol = exitCol;
	this.nRows = numRows;
	this.nCols = numCols;
	private Monster[][] monsters = new Monster[nRows][nCols];
        private Player[][] players = new Player[nRows][nCols];
        private char labyrinth[][] =  new char[nRows][nCols];
	for (int i = 0; i < nRows; i++) {
	    for (int j = 0; j < nCols; j++){
	        // Iniciar todas las referencias a null para evitar valores basura
	        // y poner el laberinto a casillas vacías
		this.monsters[i][j] = null;
		this.players[i][j] = null;
		this.labyrinth[i][j] = Labyrinth.EMPTY_CHAR;
	    }
	}


	this.labyrinth[exRow][exCol] = Labyrinth.EXIT_CHAR;
    }
```

2024-04-02 14:58 UTC, merged